# git ffmpeg-commit && git ffmpeg-push; gh ffmpeg-wrun ping.yml

name: ping
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v4
        with:
          key: bin
          path: /home/runner/.local/bin

      - name: Ping blomp + mega
        run: |
          date | tee date.txt
          rclone config dump | jq ' to_entries[] | select(
            ( .key | startswith("blomp") ) and .value.type == "alias" or
            ( .key | startswith("mega") )
            ) | "\(.key):\(.key)" ' > args
          xargs -a args -n1 -P0 rclone copyto date.txt
          xargs -a args -n1 -P0 rclone lsf --format pt --separator "  " | sort
