# git commit -am.; git push -q; yq '.files|=(sort_by(.duration)|reverse)' -oj -I0 "jobs/$title.yaml" | gh workflow run process.yml -F data=@- -f title="$title"

name: process
run-name: ${{ inputs.title }}
on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      data:
        required: true

jobs:
  process:
    name: ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJson(inputs.data).files }}

    steps:
      - uses: actions/cache/restore@v4
        with:
          key: bin
          path: /home/runner/.local/bin

      - name: Download
        run: rclone copy "${{ vars.INPUT_ROOT }}/${{ inputs.title }}" . --include="${{ matrix.file }}" -v

      - name: Process
        run: |
          ifile="${{ matrix.file }}"
          name=${ifile%.*}
          ofile="tmp/$name.mkv"
          ofile2="out/$name.mkv"
          log="out/logs/$name.log"
          report="out/reports/$name.txt"

          mkdir -p tmp out/{info,logs,images2,start2,end2,reports}

          sudo apt install -yqq libfuse2 &> /dev/null &
          shopt -s globstar; mv -n **/"$ifile" .

          ops=$( jq -r '
            (. * .files[${{ strategy.job-index }}]) | del(.files) | 
            . as {$duration, $vtrim} | .ops |
            if (.to and .to < 0) then .to += $duration end |
            if (.vf.trim.end and .vf.trim.end < 0) then .vf.trim.end += $duration end |
            .vf.trim.start = (.vf.trim.start // ((.ss // 0) + $vtrim)) |
            .vf.trim.end = (.vf.trim.end // ((.to // $duration) - $vtrim)) |
            .vf[] |= ([ to_entries[] | "\(.key)=\(.value)" ] | join(":")) |
            .vf   |= ([ to_entries[] | "\(.key)=\(.value)" ] | join(",")) |
            to_entries[] | "-" + .key, .value' << 'EOF'
            ${{ inputs.data }}EOF
          )
          
          echo $ops
          echo ${{ vars.PRESET }} | base64 -d | tee preset out/info/preset

          FFREPORT=file=%p.log:level=32 \
          ffmpeg -hide_banner -nostdin -nostats -benchmark \
          -i "$ifile" $ops -fpre preset "$ofile"

          ss=$(bc <<< $(ffprobe -v 24 -show_entries format=duration -of csv=p=0 "$ofile")-5)
          ffmpeg -v 24 -i "$ofile" -t 5 -c copy "out/start2/$name.mkv"
          ffmpeg -v 24 -vn -i "$ifile" -ss $ss -c copy "out/end2/$name.mkv"
          ffmpeg -v 24 -i "$ofile" -frames 1 -update 1 "out/images2/$name.png"

          cat preset *.log > "$log"
          wait
          { stat -c "%s %n" "$ofile"
            mkvmerge -o "$ofile2" "$ofile"
            stat -c "%s %n" "$ofile2"
          } | tee -a "$log"

          ffprobe -v 24 -show_streams -show_format -of json "$ifile" | jq -rj '[(.streams[0] | .width, .height, .r_frame_rate), (.format | .duration, .size, .bit_rate), "->", ""] | @tsv' > "$report"
          ffprobe -v 24 -show_streams -show_format -of json "$ofile2" | jq -r '[(.streams[0] | .width, .height, .r_frame_rate), (.format | .duration, .size, .bit_rate, "\"\(.filename)\"")] | @tsv' >> "$report"

      - name: Upload
        run: rclone copy out "${{ vars.OUTPUT_ROOT }}/${{ inputs.title }}" -v --no-update-modtime
